CREATE TABLE topicos (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  titulo VARCHAR(100) NOT NULL,
  mensaje VARCHAR(500) NOT NULL,
  fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) NOT NULL,
  curso VARCHAR(100) NOT NULL
);
